### PR TITLE
Fixed a bug in a ZH cross section

### PR DESCRIPTION
**Pull request by GuillelmoGomezCeballos**
Fixed a bug in a ZH cross section, it shouldn't interfere with anything else

### CODE REVIEW

**Comment by sidnarayanan** [comment]
@GuillelmoGomezCeballos , this PR conflicts with the PR I just merged from your master branch. Is this still necessary?

**Comment by GuillelmoGomezCeballos** [comment]
Mmm, it's weird there are conficts. As far as I can tell, the updated SM_leptonic file is correct

**Comment by sidnarayanan** [comment]
Should we go ahead and close this one then?

**Comment by GuillelmoGomezCeballos** [comment]
Yes, close it

**Pull request closed without merging**
