### PR TITLE
leptonic analysis

### PR DESCRIPTION
**Pull request by GuillelmoGomezCeballos**
I've commented out a few samples not needed for now, it should be a trivial merging.

### CODE REVIEW

**Comment by sidnarayanan** [comment]
Hi Guillelmo, we should either keep the samples (since there's no harm in that) or delete them. I don't think we should have commented lines of code.

**Comment by GuillelmoGomezCeballos** [comment]
Well, the only thing is that I may use it later. I guess I could keep them, and simply not to run over them. Is it what you suggest? I can look at it tomorrow

**Comment by sidnarayanan** [comment]
Yeah, we can just leave them in files.

**Comment by GuillelmoGomezCeballos** [comment]
I put back the Z processes, although I need to ask for a pull request due to the W+W+ samples (thanks :-))

**Pull request merged**
